[phases.setup]
nixPkgs = ["ffmpeg", "python312"]

[phases.install]
cmds = ["python3 -m pip install python-telegram-bot==21.10 aiohttp aiofiles yt-dlp SpeechRecognition requests psutil"]

[start]
cmd = "python3 bot.py"
